### ISSUE TITLE
Login and authentication logic

### ISSUE THREAD

**Issue by ariefrahmansyah** [unsri-hackers/ecommerce-ui#37]
Now that we have Login API ready, we can start implementing Login and Authentication logic on our web app.

1. When login success, we save the `accessToken` to `LocalStorage`
2. Whenever the user access Private Pages, the Authentication process gets the `accessToken` from `LocalStorage` and use its value to make the API call to the backend.

Hint:
1. Use `useContext` hook to simplify storing and reading the `accessToken` from `LocalStorage`

**Comment by LordAldi** [comment]
to finnish this issue, must wait backend team fix CORS issue
